catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('books/', views.books_list, name='books'),
    path('books/<int:book_id>', views.book_detail, name='book_detail'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),
    path('classification/', views.classification_list, name='classification'),
    path('classification/<int:classification_id>', views.classification_detail, name='classification_detail'),
    path('classification/lang/<int:language_id>', views.language_detail, name='language_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('search_books/', views.search_books, name='search_books'),
]

catalog/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class="search-catalog">
  <h1>Welcome to the Silberberg Library</h1>
  <form method=POST action="{% url 'catalog:search_books' %}">
    {% csrf_token %}
    <input type="search" aria-label="Search" placeholder="Search the catalog" name="searched">
    <button title="GO" type="submit"><span class="material-icons" id="search">search</span></button>
  </form>
</section>

<section class="book-gallery">
{% if books %}
  {% for book in books %}
    <div class="card">
      <a href="{% url 'catalog:book_detail' book.id %}">
        <div class="book-cover">
          {% if not book.cover_url %}
          <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="{{ book.title }}" class="book-cover">   
          {% else %}
          <img src="{{ book.cover_url }}" alt="{{ book.title }}">
          {% endif %}
        </div>
        <div class="card-container">
          <p><b>{{ book.title }}</b></p> 
          <p><i>{{book.author.first_name}} {{book.author.surname}}</i></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>
{% else %}
    <p>There are no books in the library.</p>
{% endif %}

{% endblock  %}