catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('books/', views.books_list, name='books'),
    path('books/<int:book_id>', views.book_detail, name='book_detail'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),
    path('classification/', views.classification_list, name='classification'),
    path('classification/<int:classification_id>', views.classification_detail, name='classification_detail'),
    path('classification/lang/<int:language_id>', views.language_detail, name='language_detail'),
    path('add_book/', views.add_book, name='add_book'),
    path('search_books/', views.search_books, name='search_books'),
]

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Classification(models.Model):
    """Model representing the language of a text."""
    term = models.CharField(max_length=200)

    class Meta:
        ordering = ['id']
    
    def __str__(self):
        """String for representing the Model object."""
        return self.term

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
        return reverse('classification-detail-view', args=[str(self.id)])

class Language(models.Model):
    """Model representing the language of a text."""
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
        return reverse('language-detail-view', args=[str(self.id)])

class Book(models.Model):
    """Model representing a physical book."""
    title = models.CharField(max_length=200)
    pub_year = models.CharField(max_length=4, blank=True)
    publisher = models.CharField(max_length=200, blank=True)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    cover_url = models.URLField(max_length=200, blank=True)
    summary = models.TextField(max_length=1000, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, blank=True)
    language = models.ManyToManyField(Language, blank=True)
    classification = models.ManyToManyField(Classification, blank=True)

    LOCATIONS = (
        ('PR', 'Processing'),
        ('AS', 'Astoria'),
        ('QC', 'Queens College'),
        ('SC', 'Scarsdale'),
        ('BW', 'Bushwick'),
        ('OL', 'On Loan'),
        ('XX', 'Deaccessioned'),
    )

    location = models.CharField(
        max_length=2,
        choices=LOCATIONS,
        blank=True,
        default='PR',
    )

    class Meta:
        ordering = ['date_created']
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
        return reverse('book-detail-view', args=[str(self.id)])

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=200, blank=True)
    surname = models.CharField(max_length=200)
    birth_year = models.CharField(max_length=4, blank=True)
    death_year = models.CharField(max_length=4, blank=True)

    class Meta:
        ordering = ['surname', 'first_name']
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.surname}, {self.first_name}'

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
        return reverse('author-detail-view', args=[str(self.id)])

catalog/templates/catalog/about.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<section class="about">
    <h1>About the Silberberg Library</h1>

    <div class="about-image">
        <img src="{% static '/img/eric_silberberg_cartoon.jpeg' %}" alt="Portrait of Eric Silberberg as a cartoon.">
        <figcaption>
            <a href="https://ericsilberberg.com" target="_blank" rel="noopener noreferrer">Eric Silberberg</a>, librarian.
        </figcaption>
    </div>

    <p>Welcome to the online nexus for private collections of the Silberberg family. We currently have {{ num_books }} books in our catalog on a range of topics. The library grew out of 
        <a href="#" target="_blank" rel="noopener noreferrer">Project Shelfish</a>, which is built with the Django 
        framework. We wish to extend our thanks to the 
        Internet Archive's <a href="https://openlibrary.org/" target="_blank" rel="noopener noreferrer">Open Library</a>, whose generous 
        API is a component within our cataloging process.
    </p>

</section>

{% endblock %}

catalog/templates/catalog/add_book.html
{% extends "base.html" %}
  
{% block content %}
{% load static %}



{% if submitted %}
    <section class="success-add-book">
        <p>The book was submitted successfully!</p>
        <p><a href="{% url 'catalog:add_book' %}">Add another.</a></p>
    </section>
{% else %}
    <section class="add-book">
        <h1>Add Book to Catalog</h1>
        <div class="isbn-assist">
            <h2>ISBN Assistant</h2>
            <p>Scan or enter the book's ISBN and let <a href="https://openlibrary.org/">Open Library</a> populate the form below.</p>
            <div class="isbn-input">
                <input title="Enter the ISBN" type="text" name="populate" id="populate" placeholder="ISBN">
                <button title="Populate" onclick="isbnAssist(document.getElementById('populate').value)"><span class="material-icons" id="cloud_download">cloud_download</span></button>
            </div>
        </div>
    
        <div class="add-book-form">
            <form action="" method="POST">
                {% csrf_token %}
                <h2>New Book</h2>
                <p><i>Elements in bold are required.</i></p>
            
                {{ book_form.as_p }}
                <br>
                <h2>Author</h2>
                {{ author_form.as_p }}
                <br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </section>
{% endif %}
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="return">
    <a onClick="javascript:history.go(-1);"><img src="{% static '/img/icons/back-arrow.svg' %}" alt="Go Back">Return</a>
</div>

<section class="results-container">
    <h1>Books By:</h1> 
    <p class="author-name">{{author.first_name}} {{author.surname}} ({{author.birth_year}} &#8211; {{author.death_year|default:" &nbsp;"}})</p>

    <table class="results">
        {% for book in books %}
            <tr>
                <td><p class="counter">{{ forloop.counter }}</p></td>
                <td>
                    {% if not book.cover_url %}
                    <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="Book cover">   
                    {% else %}
                    <img src="{{ book.cover_url }}" alt="Book cover">
                    {% endif %}
                </td>
                <td class="bibliography"><p class="material">BOOK</p>
                    <a href="{% url 'catalog:book_detail' book.id %}"><h2>{{ book.title }}</h2>       </a>
                    <p>{{ book.author.first_name}} {{ book.author.surname}} ({{ book.author.birth_year}} &#8211; {{book.author.death_year|default:" &nbsp;"}})</p>
                    <p>{{ book.publisher}} &#169;{{book.pub_year}}</p>
                </td>
            </tr>
        {% endfor %}
    </table>
</section>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="return">
    <a onClick="javascript:history.go(-1);"><img src="{% static '/img/icons/back-arrow.svg' %}" alt="Go Back">Return</a>
</div>

<section class="book-record">
    
    <div class="book-record-cover">
        {% if not book.cover_url %}
        <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="Image of book cover">   
        {% else %}
        <img src="{{ book.cover_url }}" alt="Image of book cover">
        {% endif %}
    </div>
    <div class="book-record-details">
        <p><b>BOOK:</b></p>
        <h1>{{book.title}}</h1>
        <dl>
            <dt>Author</dt>
            <dd><a href="{% url 'catalog:author_detail' book.author.id %}">{{book.author.first_name}} {{book.author.surname}} ({{book.author.birth_year}} &#8211; {{book.author.death_year|default:" &nbsp;"}})</a></dd>
            <dt>Publication Year</dt>
            <dd>{{book.pub_year}}</dd>
            <dt>Location</dt>
            <dd>{{book.get_location_display}}</dd>
            <dt>Subjects</dt>
                {% for term in book.classification.all  %}
                <dd><a href="{% url 'catalog:classification_detail' term.id %}">{{term}}</a></dd>
                {% endfor %}
            <dt>Language</dt>
                {% for lang in book.language.all  %}
                <dd><a href="{% url 'catalog:language_detail' lang.id %}">{{lang}}</a></dd>
                {% endfor %}
            <dt>Publisher</dt>
            <dd>{{book.publisher}}</dd>
            <dt>ISBN</dt>
            <dd>{{book.isbn}}</dd>
            <dt>Summary</dt>
            <dd>{{book.summary}}</dd>
            <br>
            <dt>Links</dt>
                <dd><a href="https://openlibrary.org/isbn/{{book.isbn}}.json">View Source Record <span class="material-icons" title="External Link" id="external">open_in_new</span></a></dd>
        </dl>
    </div>
</section>
{% endblock  %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>All Books</h1>
  {% if books %}
  <ul>
    {% for book in books %}
      <li>
        
        <a href="{% url 'catalog:book_detail' book.id %}">{{ book.title }}</a> ({{book.author.first_name}} {{book.author.surname}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/classification_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="return">
    <a onClick="javascript:history.go(-1);"><img src="{% static '/img/icons/back-arrow.svg' %}" alt="Go Back">Return</a>
</div>

<section class="results-container">
    <h1>Classification: <i>&ldquo;{{classification.term}}&rdquo;</i></h1>

    <table class="results">
        {% for book in books %}
            <tr>
                <td><p class="counter">{{ forloop.counter }}</p></td>
                <td>
                    {% if not book.cover_url %}
                    <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="Book cover">   
                    {% else %}
                    <img src="{{ book.cover_url }}" alt="Book cover">
                    {% endif %}
                </td>
                <td class="bibliography"><p class="material">BOOK</p>
                    <a href="{% url 'catalog:book_detail' book.id %}"><h2>{{ book.title }}</h2>       </a>
                    <p>{{ book.author.first_name}} {{ book.author.surname}} ({{ book.author.birth_year}} &#8211; {{book.author.death_year|default:" &nbsp;"}})</p>
                    <p>{{ book.publisher}} &#169;{{book.pub_year}}</p>
                </td>
            </tr>
        {% endfor %}
    </table>
</section>

{% endblock %}

catalog/templates/catalog/classification_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<section class="classification-system">
  <h1>Classification System</h1>
  <div class="classes">
    <div class="class">
      <div class="class-header">
        <span class="material-icons">tonality</span>
        <h2>Content</h2>
      </div>
      {% if content %}
      <ul>
        {% for c in content %}
          <li>
            <a href="{% url 'catalog:classification_detail' c.id %}">{{ c.term }}</a>
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>The classification system is not ready.</p>
      {% endif %}
    </div>
    <div class="class">
      <div class="class-header">
        <span class="material-icons">public</span>
        <h2>Geography</h2>
      </div>
        {% if geography %}
        <ul>
          {% for g in geography %}
            <li>
              <a href="{% url 'catalog:classification_detail' g.id %}">{{ g.term }}</a>
            </li>
          {% endfor %}
        </ul>
        {% else %}
          <p>The classification system is not ready.</p>
        {% endif %}
    </div>
    <div class="class">
      <div class="class-header">
        <span class="material-icons">offline_bolt</span>
        <h2>Subject</h2>
      </div>
      {% if subject %}
      <ul>
        {% for s in subject %}
          <li>
            <a href="{% url 'catalog:classification_detail' s.id %}">{{ s.term }}</a>
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>The classification system is not ready.</p>
      {% endif %}
    </div>
    <div class="class">
      <div class="class-header">
        <span class="material-icons">language</span>
        <h2>Language</h2>
      </div>
      {% if language %}
      <ul>
        {% for lang in language %}
          <li> 
            <a href="{% url 'catalog:language_detail' lang.id %}">{{ lang.name }}</a>
          </li>
        {% endfor %}
      </ul>
      {% else %}
        <p>There are no languages at this time.</p>
      {% endif %}
    </div>
  </div>
</section>



 


{% endblock %}

catalog/templates/catalog/language_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="return">
    <a onClick="javascript:history.go(-1);"><img src="{% static '/img/icons/back-arrow.svg' %}" alt="Go Back">Return</a>
</div>

<section class="results-container">
<h1>Books in: <i>&ldquo;{{ language.name }}&rdquo;</i></h1>

    <table class="results">
        {% for book in books %}
            <tr>
                <td><p class="counter">{{ forloop.counter }}</p></td>
                <td>
                    {% if not book.cover_url %}
                    <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="{{ book.title }}">   
                    {% else %}
                    <img src="{{ book.cover_url }}" alt="{{ book.title }}">
                    {% endif %}
                </td>
                <td class="bibliography"><p class="material">BOOK</p>
                    <a href="{% url 'catalog:book_detail' book.id %}"><h2>{{ book.title }}</h2>       </a>
                    <p>{{ book.author.first_name}} {{ book.author.surname}} ({{ book.author.birth_year}} &#8211; {{book.author.death_year|default:" &nbsp;"}})</p>
                    <p>{{ book.publisher}} &#169;{{book.pub_year}}</p>
                </td>
            </tr>
        {% endfor %}
    </table>
</section>

{% endblock %}

catalog/templates/catalog/search_books.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="return">
    <a onClick="javascript:history.go(-1);"><img src="{% static '/img/icons/back-arrow.svg' %}" alt="Go Back">Return</a>
</div>

<section class="results-container">
    {% if searched %}
    <h1>{{result_count}} result{{result_count|pluralize}} for <i>&ldquo;{{searched}}&rdquo;</i></h1> 

        <table class="results">
        {% for book in books %}
            <tr>
                <td><p class="counter">{{ forloop.counter }}</p></td>
                <td>
                    {% if not book.cover_url %}
                    <img src="https://www.spl.org/Seattle-Public-Library/images/books-media/default-list-icons/default-book-icon.png" alt="Book cover">   
                    {% else %}
                    <img src="{{ book.cover_url }}" alt="Book cover">
                    {% endif %}
                </td>
                <td class="bibliography"><p class="material">BOOK</p>
                    <a href="{% url 'catalog:book_detail' book.id %}"><h2>{{ book.title }}</h2>       </a>
                    <p>{{ book.author.first_name}} {{ book.author.surname}} ({{ book.author.birth_year}} &#8211; {{book.author.death_year|default:" &nbsp;"}})</p>
                    <p>{{ book.publisher}} &#169;{{book.pub_year}}</p>
                </td>
            </tr>
        {% endfor %}
        </table>

    {% else %}
    <h1>You registered an empty search</h1>
    <a href="{% url 'catalog:index' %}">Return Home</a>


    {% endif %}
</section>
{% endblock %}